### ISSUE TITLE
feature request: add a license to the template

### ISSUE THREAD

**Issue by andrewmcodes** [Ruby-Starter-Kits/Docker-Bridgetown-Generator#22]
Hey! 👋

This is a super cool project! I noticed the template doesn't have a license on it though. 

I'm definitely no expert here (is anyone??) but I am wary of using code without a license because of [this quote from an article on choosealicense.com:](https://choosealicense.com/no-permission/)

> Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. 

It would be awesome to get a license - regardless of which one you choose - so it's clear whether the code can be used for the template specifically. 

Thanks!

**Comment by MikeRogers0** [comment]
@andrewmcodes Oh good shout!

I was a bit 50/50 on adding one because I'm pretty much just running `bridgetown new .`, but I guess putting a standard MIT should be a-ok :D I'll make a PR now :)
